language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

notifications:
  slack: ril14:1AJJdLrKoybD1jjcOi3Kksct

install:
  - travis_retry composer install --no-interaction --prefer-source

script: phpunit